name: Deploy to Cloudflare Workers
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Wrangler
      run: npm install -g @cloudflare/wrangler
    - name: Authenticate Wrangler
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: wrangler login
    - name: Deploy to Cloudflare Workers
      run: wrangler publish
